### ISSUE TITLE
Cannot get double puppetting to work.

### ISSUE THREAD

**Issue by Octelly** [mautrix/meta#134]
I use both the Discord and Telegram bridges, for both I provide a random string that is specified in the ``shared_secret_authenticator.SharedSecretAuthProvider`` Synapse module. This works for both of them, but doesn't seem to work for the Meta bridge.

In my NixOS config, I have this set for Synapse (truncated):

```nix
services.matrix-synapse.settings.modules = [
  {
    module = "shared_secret_authenticator.SharedSecretAuthProvider";
    config = {
      shared_secret = "super_secret_string";
      m_login_password_support_enabled = true;
    };
  }
];
```

For the Telegram bridge, the following works (truncated):

```nix
services.mautrix-telegram.settings.bridge.login_shared_secret_map = {
    "chat.owo.digital" = "super_secret_string";
};
```

![Image](https://github.com/user-attachments/assets/4e80b6a4-7a93-435c-954d-e14cd712836e)

Same works for Discord.

![Image](https://github.com/user-attachments/assets/aedca5fd-ea41-44a8-9d85-75d1e7e50280)

As part of troubleshooting, I have tried both the newer and this older option for the Meta bridge:

```nix
services.mautrix-meta.instances.facebook.settings = {
  double_puppet.secrets."chat.owo.digital" = "as_token:super_secret_string";
  bridge.login_shared_secret_map."chat.owo.digital" = "super_secret_string";
};
```

but neither seems to have any effect.

![Image](https://github.com/user-attachments/assets/867709d3-a292-437d-80be-293f6034cdd6)

Here are the relevant parts of the yaml file that Nix generates for the bridge:

```yaml
double_puppet:
    # Servers to always allow double puppeting from.
    # This is only for other servers and should NOT contain the server the bridge is on.
    servers:
        anotherserver.example.org: https://matrix.anotherserver.example.org
    # Whether to allow client API URL discovery for other servers. When using this option,
    # users on other servers can use double puppeting even if their server URLs aren't
    # explicitly added to the servers map above.
    allow_discovery: false
    # Shared secrets for automatic double puppeting.
    # See https://docs.mau.fi/bridges/general/double-puppeting.html for instructions.
    secrets:
        chat.owo.digital: as_token:super_secret_string
```

(``login_shared_secret_map`` seems to get removed during generation by the bridge binary, which is used for corrections as part of the system build)

The ``version`` command returns: [mautrix-meta](https://github.com/mautrix/meta) v0.4.0+dev.unknown (Mon, 01 Jan 0001 00:00:00 UTC)
